<?php
/*
AUTHOR:- RITHUNAND [BENCHAMXD]
CHANNEL:- @INDUSBOTS 
THIS REPO IS LICENCED WITH GENERAL PUBLIC LICENSE VERSION:3.0
(c) RITHUNAND K
*/
$TG_BOT_TOKEN = $_ENV['1696386360:AAFMPYEKS5tdF7vY9UUrbyaPcsKEJq5-TNY'];
$BOT_NAME = $_ENV['Miss_Rani'];
$BOT_USERNAME = $_ENV['@MissRani_robot'];

?>
